### ISSUE TITLE
user namespaces enabled for garden containers preventing them from starting [migrated from diego-release]

### ISSUE THREAD

**Issue by emalm** [cloudfoundry-incubator/garden-linux-release#21]
> Original issue: https://github.com/cloudfoundry/diego-release/issues/186
> Original poster: @amartinez4

---

Hello,

The start.sh script used by garden for starting containers creates containers with or without user namespaces according to $root_uid value.

Whereas in other diego deployments, with same release and stemcell versions, $root_uid equals 0, in this case, $root_uid appears to be always different from 0. 

As a result, the command executed by start.sh is something like this:

unshare -m -- ./bin/wshd --run ./run --lib ./lib --root /var/vcap/data/garden/aufs_graph/aufs/mnt/9c66302ad37392bd49d807cb2c74ee817f67d0ae6447077a43b398430a944ddd --title "wshd: qv8beic4t11" --userns enabled

It always fails with this kind of error message:

{"timestamp":"1471352040.409447432",
"source":"garden-linux",
"message":"garden-linux.container.start.command.failed",
"log_level":2,
"data":{
    "argv":["/var/vcap/data/garden/depot/qq9lpsq22fe/start.sh"],
"error":"exit status 2",
"exit-status":2,
"handle":"executor-healthcheck-aca524c9-579d-44f2-7d00-5b40bb3ac454",
"session":"417.1.1",
"stderr":"Failed to create container: containerizer: wait for container: error: containerizer: initializing the container: system: mount proc on
 /proc: operation not permitted","stdout":"","took":"160.559707ms"}}

And strace reveals the options mount uses:

graden.mydebug.26752:212:mount("proc", "/proc", "proc", MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC, NULL) = -1 EPERM (Operation not permitted)

Since the VM is not userns capable, is this behaviour expected ?

Is there some setting that can be modified on the deployment manifest to make garden discarding user namespaces ?

We tried various versions combinations and our last failure occurs with this bunch of releases:

$ cat templates/release-versions.yml 
release_versions:
releases:
- name: diego
  version: 0.1472.0
- name: garden-linux
  version: 0.342.0
- name: etcd
  version: 49
- name: cf
  version: 237
- name: cflinuxfs2-rootfs
  version: 1.24.0
  stemcell:
  name: bosh-cloudstack-xen-ubuntu-trusty-go_agent
  version: 3232.15

And just in case it matters, I let you know we both test with 6.2 and 6.5 Xen guest tools.

Thanks for your help,

Regards.

Arnaud

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:
- [ ] [#128737417](https://www.pivotaltracker.com/story/show/128737417) user namespaces enabled for garden containers preventing them from starting [migrated from diego-release]

This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by julz** [comment]
Hi @amartinez4, 

In recent versions of cf-release all containers are unprivileged by default. More information on this change is available [in this cf-dev thread](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/7SML5PUVI2ISMOW7BONO54GVLCA6OSMQ/).

Garden does require a kernel with user namespaces enabled to create unprivileged containers. There is an option, I believe, to change the default back to privileged, but I would strongly recommend to avoid this if at all possible: unprivileged containers offer very very significant security benefits.

**Comment by amartinez-orange** [comment]
Hi,

Thanks for your quick reply,

Okay, I was confused but afterwards it seems that the kernel  does support the user namespaces:

```

# uname -r
3.19.0-64-generic
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```

```
# ls -l /proc/$$/ns/
total 0
lrwxrwxrwx 1 root root 0 Aug 24 13:13 ipc -> ipc:[4026531839]
lrwxrwxrwx 1 root root 0 Aug 24 13:13 mnt -> mnt:[4026531840]
lrwxrwxrwx 1 root root 0 Aug 24 13:13 net -> net:[4026532245]
lrwxrwxrwx 1 root root 0 Aug 24 13:13 pid -> pid:[4026531836]
lrwxrwxrwx 1 root root 0 Aug 24 13:13 user -> user:[4026531837]
lrwxrwxrwx 1 root root 0 Aug 24 13:13 uts -> uts:[4026531838]
```

```
# sysctl kernel|grep userns
kernel.unprivileged_userns_clone = 1
```

As said above, we made our tests with cf/237 but we must be prepared to what you menioned about the recent versions of cf.

Thus, it would be nice to make unprivileged containers work from now.

Back to what we face with: when updating cell's rep job, garden fails creating the container and tries to create it unprivileged (with root_uid variable different from 0) but it fails.

Now we know that eventually the VM is userns-capable, could we have done something wrong  ?

Tell me if more details are neede for further investigation on it.

Thank you very much.

Arnaud

**Comment by amartinez-orange** [comment]
Hi @julz ,

Sorry for insisting, by any chance have you any idea ?

Regards,

Arnaud

**Comment by julz** [comment]
Could you check whether you have something mounted on top of /proc in the host? Mounting /proc inside a user namespace requires that /proc is already mounted and "fully visible" in the host (basically this means there are no mounts hiding any part of it). I notice above you're using xen, is it possible /proc/xen is mounted and if so could you try unmounting it?

**Comment by f-guichard** [comment]
Hello, 

 i'm Fabien Guichard. I work with @amartinez4.

We did as you suggested and it solved our problem.

We now have to validate a long-term solution.

Many thanks.

**Comment by julz** [comment]
Excellent, great to hear @f-guichard!

**Comment by f-guichard** [comment]
In addition, we unmounted the same way as describe in https://github.com/docker/docker/issues/24752.

To give more feedbacks, here's what we've investigated : 

root@72cd5bab-c6e0-4f6a-9c34-6b00fd8b3260:/# mount | grep /proc
proc on /proc type proc (rw,noexec,nosuid,nodev)
none on /proc/xen type xenfs (rw)

Next step is to see when this fs is mounted : 

root@7a3a88a1-3ab2-4234-96ad-8a0deb697783:~# grep -r xenfs /var/log/*
/var/log/boot.log:Mounting xenfs on /proc/xen:  \* Stopping System V initi[ OK ]ion compatibility
/var/log/udev:KERNEL[6.720804] add      /module/xenfs (module)
/var/log/udev:DEVPATH=/module/xenfs
/var/log/udev:UDEV  [6.721028] add      /module/xenfs (module)
/var/log/udev:DEVPATH=/module/xenfs

Ignoring lines dealing with kernel mods, we obviously saw than this fs was mounted by somekind of magic wizard (aka SystemV init script)

Next, we brute-forced init deep-recursive search : 

root@7a3a88a1-3ab2-4234-96ad-8a0deb697783:~# egrep -i xen -R /etc/init*
/etc/init.d/xe-linux-distribution:    if [ ! -e /proc/xen/xenbus ] ; then
/etc/init.d/xe-linux-distribution:      if [ ! -d /proc/xen ] ; then
/etc/init.d/xe-linux-distribution:          action $"Mounting xenfs on /proc/xen:" /bin/false
/etc/init.d/xe-linux-distribution:          echo "Could not find /proc/xen directory."
/etc/init.d/xe-linux-distribution:          echo "You need a post 2.6.29-rc1 kernel with CONFIG_XEN_COMPAT_XENFS=y and CONFIG_XENFS=y|m"
/etc/init.d/xe-linux-distribution:          # This is needed post 2.6.29-rc1 when /proc/xen support was pushed upstream as a xen filesystem
/etc/init.d/xe-linux-distribution:          action $"Mounting xenfs on /proc/xen:" mount -t xenfs none /proc/xen
/etc/init.d/xe-linux-distribution:    if [ -e /proc/xen/capabilities ] && grep -q control_d /proc/xen/capabilities ; then
/etc/init.d/xe-linux-distribution:# fail silently if not running xen
/etc/init.d/xe-linux-distribution:if [ ! -d /proc/xen ]; then

So this special systemV script, included in package xe-guest-utilities, implies that we should be looking for some kernel mods bringing up thoses capabilities.

root@7a3a88a1-3ab2-4234-96ad-8a0deb697783:/lib/modules/3.19.0-56-generic# lsmod | grep xen
xenfs                  16384  1
xen_privcmd            16384  1 xenfs

Now we can confirm that we are loading those modules from kernel conf, not as part as modprobe :

root@7a3a88a1-3ab2-4234-96ad-8a0deb697783:/lib/modules/3.19.0-56-generic# grep XENFS /boot/config-3.19.0-56-generic
CONFIG_XENFS=m
CONFIG_XEN_COMPAT_XENFS=y

Simple workaround consists is umounting at runlevel 5 /proc/xen

We now have to decide how to finally tackle this issue for our bosh-cloudstack stemcell.
