### ISSUE TITLE
btrfs_store_size_mb can't be value of "-1"

### ISSUE THREAD

**Issue by ramelito** [cloudfoundry-incubator/garden-linux-release#6]
btrfs_store_size_mb can't be value of "-1", this leads to creating garden_graph_backing_store file of zero size and prevents from loopback creation.

**Comment by goonzoid** [comment]
-1 isn't a valid size for any data store. I don't think there's any behavior that makes sense here, given non-sensical input. I'm going to close this issue since I don't think there's any change we can make here to make this make more sense.

**Comment by ramelito** [comment]
According to spec, default value is "-1".
```
garden.btrfs_store_size_mb:
    description: "Size in MB of the BTRFS backing store for graph storage (-1 to use all available space)"
    default: -1
```
https://github.com/cloudfoundry-incubator/garden-linux-release/blob/master/jobs/garden/spec

**Comment by goonzoid** [comment]
Oh, yeah. I completely forgot about that!

So, in the default case, that gets checked here: https://github.com/cloudfoundry-incubator/garden-linux-release/blob/master/jobs/garden/templates/garden_ctl.erb#L45

If it's -1, we work out the size automatically based on the size of the disk. Is that not what you're seeing?

**Comment by ramelito** [comment]
Well, i see that bosh failed to update cell and inside vm i see that btrfs graph of zero value.

**Comment by goonzoid** [comment]
Are you setting the value in your manifest, or is this just using the default?

**Comment by ramelito** [comment]
Honestly speaking i am setting it in my manifest, you are right. It is not by design?

**Comment by goonzoid** [comment]
Well, there shouldn't ever be any need for you to do that, but I'm surprised that it causes a problem, since it's known to work fine when the default value is used.

I'll take a look into it, but in the meantime I'd simply recommend either not setting it, or setting it to a positive number.

**Comment by goonzoid** [comment]
@ramelito Just so you know, this was merged into the `develop` branch last week, but because we haven't cut a new final release since then, it's not showing up as merged here. We'll cut a release this week for sure.

**Comment by goonzoid** [comment]
@ramelito I don't think we're likely to fix this, since the fix is just "either set this to a positive value, or don't set it", so I'm going to close this issue. Let me know if there's anything else. Thanks.
